load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "kubevirt.io/kubevirt/cmd/virt-hibernation-key-service",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/hibernation/keyservice:go_default_library",
        "//pkg/hibernation/protection:go_default_library",
        "//vendor/filippo.io/age:go_default_library",
    ],
)

go_binary(
    name = "virt-hibernation-key-service",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
