//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationKeyGrant) DeepCopyInto(out *HibernationKeyGrant) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationKeyGrant.
func (in *HibernationKeyGrant) DeepCopy() *HibernationKeyGrant {
	if in == nil {
		return nil
	}
	out := new(HibernationKeyGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationKeyRegistration) DeepCopyInto(out *HibernationKeyRegistration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationKeyRegistration.
func (in *HibernationKeyRegistration) DeepCopy() *HibernationKeyRegistration {
	if in == nil {
		return nil
	}
	out := new(HibernationKeyRegistration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HibernationKeyRegistration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationKeyRegistrationList) DeepCopyInto(out *HibernationKeyRegistrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HibernationKeyRegistration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationKeyRegistrationList.
func (in *HibernationKeyRegistrationList) DeepCopy() *HibernationKeyRegistrationList {
	if in == nil {
		return nil
	}
	out := new(HibernationKeyRegistrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HibernationKeyRegistrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationKeyRegistrationSpec) DeepCopyInto(out *HibernationKeyRegistrationSpec) {
	*out = *in
	if in.RequestedVMs != nil {
		in, out := &in.RequestedVMs, &out.RequestedVMs
		*out = make([]RequestedVM, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationKeyRegistrationSpec.
func (in *HibernationKeyRegistrationSpec) DeepCopy() *HibernationKeyRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(HibernationKeyRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HibernationKeyRegistrationStatus) DeepCopyInto(out *HibernationKeyRegistrationStatus) {
	*out = *in
	if in.EffectiveGrants != nil {
		in, out := &in.EffectiveGrants, &out.EffectiveGrants
		*out = make([]HibernationKeyGrant, len(*in))
		copy(*out, *in)
	}
	if in.CertificateExpiry != nil {
		in, out := &in.CertificateExpiry, &out.CertificateExpiry
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HibernationKeyRegistrationStatus.
func (in *HibernationKeyRegistrationStatus) DeepCopy() *HibernationKeyRegistrationStatus {
	if in == nil {
		return nil
	}
	out := new(HibernationKeyRegistrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestedVM) DeepCopyInto(out *RequestedVM) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestedVM.
func (in *RequestedVM) DeepCopy() *RequestedVM {
	if in == nil {
		return nil
	}
	out := new(RequestedVM)
	in.DeepCopyInto(out)
	return out
}
