/*
This file is part of the KubeVirt project

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Copyright The KubeVirt Authors.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	hibernationv1alpha1 "kubevirt.io/api/hibernation/v1alpha1"
	scheme "kubevirt.io/client-go/kubevirt/scheme"
)

// HibernationKeyRegistrationsGetter has a method to return a HibernationKeyRegistrationInterface.
// A group's client should implement this interface.
type HibernationKeyRegistrationsGetter interface {
	HibernationKeyRegistrations() HibernationKeyRegistrationInterface
}

// HibernationKeyRegistrationInterface has methods to work with HibernationKeyRegistration resources.
type HibernationKeyRegistrationInterface interface {
	Create(ctx context.Context, hibernationKeyRegistration *hibernationv1alpha1.HibernationKeyRegistration, opts v1.CreateOptions) (*hibernationv1alpha1.HibernationKeyRegistration, error)
	Update(ctx context.Context, hibernationKeyRegistration *hibernationv1alpha1.HibernationKeyRegistration, opts v1.UpdateOptions) (*hibernationv1alpha1.HibernationKeyRegistration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hibernationKeyRegistration *hibernationv1alpha1.HibernationKeyRegistration, opts v1.UpdateOptions) (*hibernationv1alpha1.HibernationKeyRegistration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*hibernationv1alpha1.HibernationKeyRegistration, error)
	List(ctx context.Context, opts v1.ListOptions) (*hibernationv1alpha1.HibernationKeyRegistrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *hibernationv1alpha1.HibernationKeyRegistration, err error)
	HibernationKeyRegistrationExpansion
}

// hibernationKeyRegistrations implements HibernationKeyRegistrationInterface
type hibernationKeyRegistrations struct {
	*gentype.ClientWithList[*hibernationv1alpha1.HibernationKeyRegistration, *hibernationv1alpha1.HibernationKeyRegistrationList]
}

// newHibernationKeyRegistrations returns a HibernationKeyRegistrations
func newHibernationKeyRegistrations(c *HibernationV1alpha1Client) *hibernationKeyRegistrations {
	return &hibernationKeyRegistrations{
		gentype.NewClientWithList[*hibernationv1alpha1.HibernationKeyRegistration, *hibernationv1alpha1.HibernationKeyRegistrationList](
			"hibernationkeyregistrations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *hibernationv1alpha1.HibernationKeyRegistration {
				return &hibernationv1alpha1.HibernationKeyRegistration{}
			},
			func() *hibernationv1alpha1.HibernationKeyRegistrationList {
				return &hibernationv1alpha1.HibernationKeyRegistrationList{}
			},
		),
	}
}
